#plugins: []
#plugins:
#    - {name: static_map,       type: "costmap_2d::StaticLayer"}
#global_frame: map
#robot_base_frame: base_link
#update_frequency: 5.0
#publish_frequency: 1.0
#always_send_full_costmap: true

#set if you want the voxel map published
#publish_voxel_map: false

#set to true if you want to initialize the costmap from a static map
static_map: true

#static_layer:
#    map_topic: map
#    first_map_only: true
#    trinary_costmap: false
#    publish_frequency: 1.0
#    footprint: [[-0.205, -0.145], [-0.205, 0.145], [0.077, 0.145], [0.077, -0.145]]
#    inflation_radius: 0.20
#    cost_scaling_factor: 0.5



transform_tolerance: 0.3
obstacle_range: 2.5
max_obstacle_height: 2.0
raytrace_range: 3.0
footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]
robot_radius: 0.46
footprint_padding: 0.01
inflation_radius: 0.55
cost_scaling_factor: 10.0
lethal_cost_threshold: 100
#observation_sources: base_scan
#base_scan: {data_type: LaserScan, expected_update_rate: 0.4,
#  observation_persistence: 0.0, marking: true, clearing: true, max_obstacle_height: 0.4, min_obstacle_height: 0.08}
